---
apiVersion: v1
kind: Service
metadata:
  name: landing
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: landing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: jesselurie6/competitors-club-landing:v1.0.0
          ports:
            - containerPort: 3000
