apiVersion: v1
kind: Service
metadata:
  name: node0
spec:
  ports:
  - name: wss
    port: 9944
    targetPort: 9944
  - name: rpc
    port: 9933
    targetPort: 9933
  - name: p2p
    port: 30333
    targetPort: 30333
  selector:
    app: node0
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node0
  template:
    metadata:
      labels:
        app: node0
    spec:
      containers:
        - name: cc-node-container
          image: jesselurie6/competitors-club:v1.0.0
          # volumeMounts:
          # - mountPath: "/competitors-club"
          #   name: cc-pvc
          args: ["--name","cc-node-0", "--base-path","/competitors-club", "--port","30333","--ws-port","9944","--rpc-port", "9933","--validator","--unsafe-ws-external", "--unsafe-rpc-external", "--rpc-methods", "Unsafe",   "--ws-external",    "--rpc-external", "--rpc-cors", "all"]
          ports:
          # - containerPort: 9944
          - name: p2p
            containerPort: 30333
          - name: rpc
            containerPort: 9933
          - name: wss
            containerPort: 9944
          env:
          - name: MESSAGE
            value: Hello from the second deployment!
      # volumes:
      #   - name: cc-node0-volume
      #     persistentVolumeClaim:
      #       claimName: cc-pvc 